name: Fetch All Teams

# Executa todos os dias às 23:50 no horário local (UTC-3), o que corresponde a 02:50 UTC
on:
  schedule:
    - cron: '50 02 * * *'

jobs:
  fetch-teams:
    runs-on: ubuntu-latest
    steps:
      - name: Call API to fetch all teams
        run: curl -X POST https://tabelona-api.onrender.com/teams/cron
