name: Fetch All Teams

# Executa a cada dia às 20:21
on:
  schedule:
    - cron: '21 20 * * *'

jobs:
  fetch-teams:
    runs-on: ubuntu-latest
    steps:
      - name: Call API to fetch all teams
        run: curl -X POST https://tabelona-api.vercel.app/teams/cron
